2014/01/06 17:36:24 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[42000] [1049] Unknown database 'testdrive'' in /var/www/push_articles/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/push_articles/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/push_articles/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/push_articles/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/push_articles/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /var/www/push_articles/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /var/www/push_articles/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /var/www/push_articles/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /var/www/push_articles/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /var/www/push_articles/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /var/www/push_articles/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /var/www/push_articles/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/push_articles/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/push_articles/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /var/www/push_articles/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /var/www/push_articles/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/push_articles/testdrive/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/push_articles/testdrive/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/push_articles/testdrive/index.php?r=gii/default/index
---
2014/01/06 18:14:47 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity._id" is not defined.' in /var/www/push_articles/yii/framework/base/CComponent.php:173
Stack trace:
#0 /var/www/push_articles/testdrive/protected/components/UserIdentity.php(28): CComponent->__set('_id', '1')
#1 /var/www/push_articles/testdrive/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#2 /var/www/push_articles/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 /var/www/push_articles/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 /var/www/push_articles/yii/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 /var/www/push_articles/testdrive/protected/controllers/SiteController.php(94): CModel->validate()
#6 /var/www/push_articles/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#7 /var/www/push_articles/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#8 /var/www/push_articles/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#9 /var/www/push_articles/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 /var/www/push_articles/yii/framework/web/CWebApplication.php(282): CController->run('login')
#11 /var/www/push_articles/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#12 /var/www/push_articles/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#13 /var/www/push_articles/testdrive/index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/push_articles/testdrive/index.php?r=site/login
HTTP_REFERER=http://localhost/push_articles/testdrive/index.php?r=site/login
---
2014/01/06 18:16:43 [error] [system.db.CDbCommand] CDbCommand::fetch() failed: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'usr_username' in 'where clause'. The SQL statement executed was: SELECT * FROM `tbl_user` `t` WHERE LOWER(usr_username)=? LIMIT 1.
in /var/www/push_articles/testdrive/protected/components/UserIdentity.php (35)
in /var/www/push_articles/testdrive/protected/models/LoginForm.php (52)
in /var/www/push_articles/testdrive/protected/controllers/SiteController.php (94)
2014/01/06 18:16:43 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'usr_username' in 'where clause'. The SQL statement executed was: SELECT * FROM `tbl_user` `t` WHERE LOWER(usr_username)=? LIMIT 1' in /var/www/push_articles/yii/framework/db/CDbCommand.php:543
Stack trace:
#0 /var/www/push_articles/yii/framework/db/CDbCommand.php(415): CDbCommand->queryInternal('fetch', Array, Array)
#1 /var/www/push_articles/yii/framework/db/ar/CActiveRecord.php(1351): CDbCommand->queryRow()
#2 /var/www/push_articles/yii/framework/db/ar/CActiveRecord.php(1456): CActiveRecord->query(Object(CDbCriteria))
#3 /var/www/push_articles/testdrive/protected/components/UserIdentity.php(35): CActiveRecord->find('LOWER(usr_usern...', Array)
#4 /var/www/push_articles/testdrive/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#5 /var/www/push_articles/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#6 /var/www/push_articles/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#7 /var/www/push_articles/yii/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#8 /var/www/push_articles/testdrive/protected/controllers/SiteController.php(94): CModel->validate()
#9 /var/www/push_articles/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#10 /var/www/push_articles/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#11 /var/www/push_articles/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#12 /var/www/push_articles/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /var/www/push_articles/yii/framework/web/CWebApplication.php(282): CController->run('login')
#14 /var/www/push_articles/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#15 /var/www/push_articles/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#16 /var/www/push_articles/testdrive/index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/push_articles/testdrive/index.php?r=site/login
HTTP_REFERER=http://localhost/push_articles/testdrive/index.php?r=site/login
---
2014/01/06 18:16:57 [error] [exception.CException] exception 'CException' with message 'Property "User.usr_status" is not defined.' in /var/www/push_articles/yii/framework/base/CComponent.php:130
Stack trace:
#0 /var/www/push_articles/yii/framework/db/ar/CActiveRecord.php(145): CComponent->__get('usr_status')
#1 /var/www/push_articles/testdrive/protected/components/UserIdentity.php(42): CActiveRecord->__get('usr_status')
#2 /var/www/push_articles/testdrive/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#3 /var/www/push_articles/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 /var/www/push_articles/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 /var/www/push_articles/yii/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 /var/www/push_articles/testdrive/protected/controllers/SiteController.php(94): CModel->validate()
#7 /var/www/push_articles/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#8 /var/www/push_articles/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#9 /var/www/push_articles/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#10 /var/www/push_articles/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 /var/www/push_articles/yii/framework/web/CWebApplication.php(282): CController->run('login')
#12 /var/www/push_articles/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#13 /var/www/push_articles/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#14 /var/www/push_articles/testdrive/index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/push_articles/testdrive/index.php?r=site/login
HTTP_REFERER=http://localhost/push_articles/testdrive/index.php?r=site/login
---
2014/01/06 18:18:41 [error] [system.db.CDbCommand] CDbCommand::fetch() failed: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'usr_username' in 'where clause'. The SQL statement executed was: SELECT * FROM `tbl_user` `t` WHERE LOWER(usr_username)=? LIMIT 1.
in /var/www/push_articles/testdrive/protected/components/UserIdentity.php (23)
in /var/www/push_articles/testdrive/protected/models/LoginForm.php (52)
in /var/www/push_articles/testdrive/protected/controllers/SiteController.php (94)
2014/01/06 18:18:41 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'usr_username' in 'where clause'. The SQL statement executed was: SELECT * FROM `tbl_user` `t` WHERE LOWER(usr_username)=? LIMIT 1' in /var/www/push_articles/yii/framework/db/CDbCommand.php:543
Stack trace:
#0 /var/www/push_articles/yii/framework/db/CDbCommand.php(415): CDbCommand->queryInternal('fetch', Array, Array)
#1 /var/www/push_articles/yii/framework/db/ar/CActiveRecord.php(1351): CDbCommand->queryRow()
#2 /var/www/push_articles/yii/framework/db/ar/CActiveRecord.php(1456): CActiveRecord->query(Object(CDbCriteria))
#3 /var/www/push_articles/testdrive/protected/components/UserIdentity.php(23): CActiveRecord->find('LOWER(usr_usern...', Array)
#4 /var/www/push_articles/testdrive/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#5 /var/www/push_articles/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#6 /var/www/push_articles/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#7 /var/www/push_articles/yii/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#8 /var/www/push_articles/testdrive/protected/controllers/SiteController.php(94): CModel->validate()
#9 /var/www/push_articles/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#10 /var/www/push_articles/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#11 /var/www/push_articles/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#12 /var/www/push_articles/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /var/www/push_articles/yii/framework/web/CWebApplication.php(282): CController->run('login')
#14 /var/www/push_articles/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#15 /var/www/push_articles/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#16 /var/www/push_articles/testdrive/index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/push_articles/testdrive/index.php?r=site/login
HTTP_REFERER=http://localhost/push_articles/testdrive/index.php?r=site/login
---
